version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22.x
    commands:
      - apt-get update -y
      - apt-get install -y hugo
  pre_build:
    commands:
      - npm ci
  build:
    commands:
      - npm run build --if-present
      - tar -czf "website.tar.gz" -C public .

artifacts:
  files: 
    - website.tar.gz
  name: website-${CODEBUILD_RESOLVED_SOURCE_VERSION:-unknown}
