baseURL = 'https://alexmcnall.co.uk'
locale = 'en-gb'
title = 'Alex McNall'
theme = 'LucentLink-Hugo'
minVersion = '0.162.1'

[params]
  description = "Alex McNall's webpage with links to his projects."

[taxonomies]

[outputs]
  home = ['HTML']
