baseURL = 'https://alexmcnall.co.uk/'
languageCode = 'en-gb'
title = "Alex McNall"
sectionPagesMenu = 'main'
theme = 'dario'

[security]
  enableInlineShortcodes = true

[params]
    description = 'Personal website of Alex McNall'
    disableFontPreload = true

    [params.author]
        name = 'Alex Stuart McNall'
        email = 'asm@alexmcnall.co.uk'

[menu]
  [[menu.footer]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/alex-mcnall"
    weight = 1
